---
- name: Setup Server
  hosts: 192.168.1.10
  become: true

  tasks:
   - name: Add epel-release repo
     yum:
       name: epel-release
       state: present

   - name: Install filebeat
     yum:
      name: filebeat
      state: present

   - name: Enable filebeat
     systemd:
       name: filebeat
       enabled: yes
       
   - name: Yum upgrade all
     yum:
       name: '*'
       state: latest

   - name: Install packages
     yum:
       name: "{{ item }}"
       state: present
     with_items:
      - vim

  roles:
    - filebeat_install
