---
- name: Add ansible user
  user:
    name: ansible
    groups: sudo
    shell: /bin/bash
    password: "ansible"

- name: Add ansible user to sudoers
  copy:
    dest: "/etc/sudoers.d/ansible"
    content: "ansible ALL=(ALL) NOPASSWD: ALL"

- name: Add user dylan
  user:
    name: dylan
    groups: sudo
    shell: /bin/bash
    password: "changeme"

- name: Add user dylan to sudoers
  copy:
    dest: "/etc/sudoers.d/ansible"
    content: "dylan ALL=(ALL) NOPASSWD: ALL"

- name: Restart ssh
  systemd:
    name: sshd
    state: restarted
