---
- name: Add user dylan
  user:
    name: dylan
    password: changeme
    comment: Dylan Sigler
    group: admin

- name: Create 2048-bit SSH key for dylan
  user:
    name: dylan
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Add user docker
  user:
    name: docker
    password: changeme
    comment: Docker User
    hidden: yes