- name: Add ansible user
  user:
    name: ansible
    shell: /bin/bash
    password: "ansible"

- name: Add ansible user to sudoers
  copy:
    dest: "/etc/sudoers.d/ansible"
    content: "devops ALL=(ALL) NOPASSWD: ALL"

- name: Restart ssh
  systemd:
    name: sshd
    state: restarted
