---
- name: Ensure wheel group exists
  group:
    name: wheel
    state: present
    
- name: Give wheel group passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add user dylan
  user:
    name: dylan
    password: changeme
    comment: Dylan Sigler
    group: wheel

- name: Create 2048-bit SSH key for dylan
  user:
    name: dylan
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Add user docker
  user:
    name: docker
    password: changeme
    comment: Docker User
    hidden: yes
