---
- name: Yum upgrade all
yum:
    name: '*'
    state: latest

- name: Install packages
yum:
    name: 
    - vim
    - wireshark
    - clamav
    - htop
    - gcc
    - java
    - nmap
    - wget
    state: present