---
- name: Yum upgrade all
  yum:
    name: '*'
    state: latest

- name: Enable epel-release
  yum:
    name: epel-release
    state: present

- name: Install packages
  yum:
    name: 
    - vim
    - wireshark
    - htop
    - gcc
    - java
    - nmap
    - wget
    state: present
