---
- name: Remove old versions
  yum:
    name:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine
    - docker-ce
    - docker-ce-cli
    state: absent

- name: Remove old files
  file:
    path: /var/lib/docker
    state: absent
